# Generated by Django 3.2.7 on 2021-09-16 13:34

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=400)),
                ('comment', models.CharField(default='None', max_length=1000)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Silverbazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=250)),
                ('silver', models.IntegerField(default=0)),
                ('costpersilver', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=100)),
                ('header', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('free', models.BooleanField(default=True)),
                ('silver', models.IntegerField(default=0, null=True)),
                ('silverclick', models.IntegerField(default=0)),
                ('silverimpression', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('moneyclick', models.IntegerField(default=0)),
                ('moneyimpression', models.IntegerField(default=0)),
                ('silver_banus', models.IntegerField(default=0)),
                ('money_banus', models.IntegerField(default=0)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('shares', models.IntegerField(blank=True, default=0, null=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_visiters', models.IntegerField(default=0)),
                ('clicks', models.ManyToManyField(related_name='clicks', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(default=0, related_name='comments', to='paisafin.Comments')),
                ('impressions', models.ManyToManyField(related_name='impressions', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=100)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('password', models.TextField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('number2', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('moneybalance', models.IntegerField(default=0)),
                ('silverbalance', models.IntegerField(default=0)),
                ('mymoney', models.IntegerField(default=0)),
                ('mysilvers', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=1000)),
                ('brandname', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('pinterest', models.CharField(max_length=100, null=True)),
                ('youtube', models.CharField(max_length=100, null=True)),
                ('ads', models.IntegerField(default=0)),
                ('likes', models.CharField(default=0, max_length=100)),
                ('rating', models.CharField(default=0, max_length=100)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paisafin.country')),
                ('followers', models.ManyToManyField(default=0, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paisafin.language')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paisafin.type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
