# Generated by Django 3.2 on 2021-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('url', models.TextField()),
                ('description', models.TextField()),
                ('money', models.BooleanField(default=False)),
                ('silver', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=False)),
            ],
        ),
    ]
