# Generated by Django 3.2 on 2021-05-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='header',
            field=models.CharField(max_length=100),
        ),
    ]
