# Generated by Django 3.2.7 on 2021-09-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0002_countrysasa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countrysasa',
        ),
    ]
