# Generated by Django 3.2 on 2021-05-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0002_alter_destination_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='moneyclick',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='moneyimpression',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='silverclick',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='silverimpression',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='silver',
            field=models.IntegerField(),
        ),
    ]
