# Generated by Django 3.2 on 2021-05-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0003_auto_20210505_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(max_length=25),
        ),
    ]
