# Generated by Django 3.2 on 2021-05-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0004_alter_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='silver',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
