# Generated by Django 3.2 on 2021-05-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0005_alter_destination_silver'),
    ]

    operations = [
        migrations.CreateModel(
            name='all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('moneybalance', models.IntegerField()),
                ('silverbalance', models.IntegerField()),
                ('mybalance', models.IntegerField()),
            ],
        ),
    ]
