# Generated by Django 3.2 on 2021-05-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0007_auto_20210505_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='moneybalance',
        ),
        migrations.RemoveField(
            model_name='all',
            name='mybalance',
        ),
        migrations.RemoveField(
            model_name='all',
            name='silverbalance',
        ),
    ]
