# Generated by Django 3.2 on 2021-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0008_auto_20210505_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='moneybalance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all',
            name='mybalance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all',
            name='silverbalance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
