# Generated by Django 3.2 on 2021-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0009_auto_20210505_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='moneybalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all',
            name='mybalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all',
            name='silverbalance',
            field=models.IntegerField(default=0),
        ),
    ]
