# Generated by Django 3.2 on 2021-05-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0010_auto_20210505_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField()),
            ],
        ),
    ]
