# Generated by Django 3.2 on 2021-05-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0011_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
