# Generated by Django 3.2 on 2021-05-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0013_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
