# Generated by Django 3.2 on 2021-05-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0015_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('requiredemail', models.EmailField(max_length=100)),
                ('optionalemail', models.EmailField(max_length=100)),
                ('countrycode', models.CharField(max_length=100)),
                ('firstnumber', models.CharField(max_length=100)),
                ('secondnumber', models.CharField(max_length=100)),
                ('enterpassword', models.TextField()),
                ('reenterpassword', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('is_Gaming', models.BooleanField(default=False, verbose_name='Gaming')),
                ('website', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('pinterest', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
            ],
        ),
    ]
