# Generated by Django 3.2 on 2021-05-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0016_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='is_Gaming',
            new_name='interest',
        ),
        migrations.RemoveField(
            model_name='update',
            name='reenterpassword',
        ),
    ]
