# Generated by Django 3.2 on 2021-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paisafin', '0017_auto_20210509_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='interest',
            field=models.BooleanField(default=False, verbose_name='product'),
        ),
    ]
